### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by bthirion** [pneuvial/sanssouci.python#1]
before trying to do anything on the library, we need to make sure we're not breaking it. For that, we need to have unit tests.

**Comment by pneuvial** [comment]
see pytest.org

**Comment by bthirion** [comment]
Do you want help on that ?
I can draft a first example.

**Comment by pneuvial** [comment]
Sure, your help is welcome!

**Comment by pneuvial** [comment]
Addressed by #9
