### ISSUE TITLE
Implement one-sample tests

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/sanssouci.python#13]
Currently `get_perm_p` only handles two-sample tests.  In order to implement one-sample tests, one can create a dedicated function `get_perm_p_1s` One-sample tests can be implemented via a dedicated function `get_perm_p_1s` (or `get_one_sided_perm_p` mirroring `get_perm_p` (https://github.com/pneuvial/sanssouci.python/blob/582b097682334a6ca44d247f3805742f54d00afb/sanssouci/lambda_calibration.py#L13).

**Comment by alexblnn** [comment]
addressed in #20, you can close this @pneuvial
