### ISSUE TITLE
Vectorize calibration for any template

### ISSUE THREAD

**Issue by alexblnn** [pneuvial/sanssouci.python#24]
Since PR #22 we use a loop in the calibration function to apply the inverse templates : 

`tkInv_all = np.array([t_inv(p0[:, i], i + 1, p) for i in range(p)]).T`

Perhaps this could be avoided. We can see that easily in the linear case, but the general case is not trivial (for example, for beta templates)

**Comment by bthirion** [comment]
As far as I can see, the fix would be to have `t_inv` accept an array as a second argument. `t_inv` would perform the loop internally; I guess that for some templates it can be vectorized easily.

**Comment by pneuvial** [comment]
too low priority.
