### ISSUE TITLE
Potential bug when using maxFP/curve_max_FP

### ISSUE THREAD

**Issue by alexblnn** [pneuvial/sanssouci.python#30]
we need to be careful using the k_min idea (see https://github.com/pneuvial/sanssouci.python/pull/29) and computing bounds. If a sliced template (i.e. thr[k_min:]) is given as input to maxFP or curve_max_FP we give over optimistic bounds, since those functions assume that the templates starts at k=1 (see https://github.com/pneuvial/sanssouci.python/blob/main/sanssouci/post_hoc_bounds.py#L56)

**Comment by pneuvial** [comment]
As discussed a workaround seems to force thr[0:(k_min-1)] to be 0 instead of slicing the template. This should have the effect to make the k < k_min suboptimal in the calculation of the bound.

**Comment by pneuvial** [comment]
The k_min idea has been abandoned.
