### ISSUE TITLE
Wrong assumption in calibrate_jer

### ISSUE THREAD

**Issue by alexblnn** [pneuvial/sanssouci.python#32]
calibrate_jer assumes that there exists a template in learned_templates such that JER<alpha, which is not always the case. If it is not the case, the dichotomy needs to be aborted (and raise an error) and this is not the case right now.

**Comment by pneuvial** [comment]
Similarly, should there be a special treatment for the case where all templates in learned_templates are such that JER<alpha ?  In that case the JER budget is not exhausted by the templates, it may be useful to warn users for this?
